registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
   # REGISTRY_HTTP_TLS_CERTIFICATE: /certs/certificate.crt
   #  REGISTRY_HTTP_TLS_KEY: /certs/privateKey.key
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - /home/devops/data:/var/lib/registry
    - /home/devops/certs:/certs
    - /home/devops/auth:/auth
